name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        db:
          - mysql
          - postgresql
          - sqlite3
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: [3.1, 3.2, 3.3, 3.4, head, truffleruby]
        rails: ['~> 6.1.0', '~> 7.0.0', '~> 8.0.0', '>= 0']
        exclude:
          - rails: '~> 8.0.0'
            ruby: 3.1
    runs-on: ubuntu-latest
    env:
      CI_RAILS_VERSION: ${{ matrix.rails }}
      ACTIVE_RECORD_ADAPTER: ${{ matrix.db }}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: '127.0.0.1'
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: acts_as_nosql
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports: ['3306:3306']
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - if: ${{ matrix.db == 'mysql' }}
      name: Setup MySQL
      run: |
        mysql -uroot --host=127.0.0.1 -e "CREATE DATABASE acts_as_nosql CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci"

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rspec
